theme: jekyll-theme-cayman
title: Computer Science

#tabs
main:
  - title: "Quick-Start Guide"
    url: 
  - title: "Posts"
    url:
  - title: "Categories"
    url: 
  - title: "Tags"
    url: 
  - title: "Pages"
    url: 
  - title: "Collections"
    url: 
  - title: "External Link"
    url: 
