# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Computer Science
tagline:          'CS'
description:      'Coding'
url:              https://aidanho1188.github.io/MyWebpage/

author:
  name:           'Aidan'
  url:            https://aidanho1188.github.io/MyWebpage/

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/aidanho1188/MyWebpage/
